### ISSUE TITLE
Hillary - cracked rigger

### ISSUE THREAD

**Issue by p-verrier** [CityRC/Equipment#101]
There's a crack in the bowside/starboard rigger on Hillary, near where it's attached to the boat (end nearest to the stern I think).

**Comment by CCRCJuniors** [comment]
Hi there,

I haven't been down to look at the boat but the juniors are due to race in this on Sat at Sudbury. Benedict, have you had a chance to look at the damage? 

Cheers
Tammy

**Comment by 13enedict** [comment]
There's what looks like a metal crack on the aft end of the bowside rigger. It's probably been there quite a while but it is going to fail sooner or later. I don't think that it should be raced. @JackLA, what do you think?

![image](https://cloud.githubusercontent.com/assets/9012054/17306315/5f26338a-5827-11e6-9dc1-205fd3df5a78.png)

**Comment by p-verrier** [comment]
It also seems to be pulling to strokeside quite badly - but it's been doing that for the last few months, might be related to the cracked rigger though.


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Benedict <notifications@github.com> Date: 01/08/2016  20:37  (GMT+00:00) To: CityRC/Equipment <Equipment@noreply.github.com> Cc: p-verrier <patricia.e.verrier@gmail.com>, Author <author@noreply.github.com> Subject: Re: [CityRC/Equipment] Hillary - cracked rigger (#101) 
There's what looks like a metal crack on the aft end of the bowside rigger. It's probably been there quite a while but it is going to fail sooner or later. I don't think that it should be raced. @JackLA, what do you think?

**Comment by 13enedict** [comment]
Put a gun to my head and I'd guess the pitch on the gate is out

**Comment by 13enedict** [comment]
Rigger has been welded
