### ISSUE TITLE
Kieran West Bow Seat Foot Plate Track

### ISSUE THREAD

**Issue by theonlyedward** [CityRC/Equipment#107]
The indexed track on the bow side of the bow seat in the boat Kieran West has detached from the boat. Thus, the foot plate may only be attached on one side. This is the black plastic track with notches that the foot plate screws onto. The holes in the boat that the track is bolted to have been warn away and the nets holding the bolts in place can fit through. Subsequently the track has come off. An attempt was made to repair the problem but we were unable to find bolts that would fit into the holes and were long enough to add washers. It should be possible to reattached the track with longer bolts, nuts, and larger diameter washers.

**Comment by 13enedict** [comment]
I assess the foot stretcher but I don't see the adjuster track. Where is it? It's actually pretty important as they don't make them in that size any more

**Comment by theonlyedward** [comment]
Hi Benedict,

We saw a few others on the work bench in the back of the boat house and I
believe we left it with them. I don't recall a specific location beyond
that.

Best,
Ed

**Comment by 13enedict** [comment]
Replaced adjuster channel and secured by screwing into a length of wood. Also replaced shoes
