### ISSUE TITLE
CAM321 Redeham and Weep needs new gates

### ISSUE THREAD

**Issue by LauraClack** [CityRC/Equipment#11]
As discussed please can we have a full set of new gates for this boat - I missed this off the original list. I can fit them when I check the rigging.

Also some holes in the decking around some of the seats + hole in the canvas under the stroke seat. Needs some filler - does not need professional repair.

**Comment by 13enedict** [comment]
OK, I think we actually have suitable gates. @umarndt could you take a look at them (with @LauraClack if poss) and then sort out getting them fitted? I'll show you where the spares are, if necessary.

Also, the coach mentioned that there might be an issue with stroke's pin. If this is the case, it needs to be logged.

Finally, the holes need to logged in a separate issue (sorry, please don't hate me).
OK, I think we actually have suitable gates. @umarndt could you take a look at them (with @LauraClack if poss) and then sort out getting them fitted? I'll show you where the spares are, if necessary.

Also, John Upton(I think) mentioned that there might be an issue with stroke's pin. If this is the case, it needs to be logged.

Finally, the holes need to logged in a separate issue (sorry, please don't hate me).

**Comment by umarndt** [comment]
No problem.

**Comment by 13enedict** [comment]
We actually do have new gates and inserts for this. @umarndt  would you have time to organise fitting these?
