### ISSUE TITLE
Doreen bow cracked

### ISSUE THREAD

**Issue by Jess-upton** [CityRC/Equipment#110]
Hi,
I noticed last week that there is a pretty decent crack/dent in the bows of Doreen (possibly from mounting another boat!). Not sure if it had been reported so doing so now.
I put some tape on it for the time being
Jess

**Comment by Jess-upton** [comment]
![img_2214](https://cloud.githubusercontent.com/assets/21200856/17898196/bf3213ec-694e-11e6-8d9a-17f7f10b8b3e.JPG)

**Comment by tristanjph2** [comment]
Has this been fixed yet? Christ summer boat is supposed to be racing the great Ouse marathon in this on Sunday...
