### ISSUE TITLE
Wholly bow ball

### ISSUE THREAD

**Issue by Jess-upton** [CityRC/Equipment#111]
Hi
Wholly has lots its bow ball (again) - bow needs a bit of a rebuild in order for us to be able to screw a new one on properly.
Jess

**Comment by Jess-upton** [comment]
Hi
Any update?  Last night the boat still did not have a bowball - a temporary one has been taped on.
Jess

**Comment by 13enedict** [comment]
Glued and screwed an XL bowball

**Comment by johnwalley** [comment]
Wholly had no bowball when it was taken out at 2pm on Sunday.

**Comment by 13enedict** [comment]
Are you kidding me?! I bolted and glued a new extra large one like a week ago. 😡😡😡😡

**Comment by johnwalley** [comment]
The piece where it is bolted on was still there but the ball itself was gone

**Comment by Jess-upton** [comment]
Hi, I know this is annoying, but can you confirm if this has been fixed?
I saw video of the girls boating for the Christmas Head and it looked like Wholly didn't have a bowball.
Jess
