### ISSUE TITLE
Kieren West Issues

### ISSUE THREAD

**Issue by tristanjph2** [CityRC/Equipment#112]
Slider won't move 7/5 seat (currently at different positions
5 foot plates moving, I think the notched bar is loose
Mystery clunking in the bow seat from the rigger, could be an issue with the gate
Large hole in the shoes in the bow seat
Small chunk missing from bow seat saxboard (opposite rigger) causing cuts on rowers hands

**Comment by 13enedict** [comment]
- The sliders are held in place by two wing nuts each, it looks like whomever only loosened one (the rear one).
- Couldn't repro moving footplate
- Replaced bow seat shoes
- I'll tape up the sax board at some point - the boat has a limited life span at City. Also, tell the rower that if they're cutting themselves on it, they're doing something wrong.
