### ISSUE TITLE
The Natural 

### ISSUE THREAD

**Issue by JackLA** [CityRC/Equipment#114]
Shoulder bolts need to be replaced with twin bolts (plate mounted bolts) as the current individual bolts will destroy the shoulders

**Comment by 13enedict** [comment]
I ordered these and they have arrived but there was some miscommunication and they have sent me one double bolt, not one boat's worth. This is technically better than nothing.

**Comment by 13enedict** [comment]
Ok, so there's been a bit of confusion about bolts but more are on the way

**Comment by 13enedict** [comment]
Fitted new bolts
