### ISSUE TITLE
John Henry steering, shoes and runners

### ISSUE THREAD

**Issue by pworth68** [CityRC/Equipment#117]
1.The rudder is almost impossible to turn. The shoes are so lax that any intorsion just causes the shoe to bend, without moving the footplate. ?new shoes? 
2. The rudder mechanism itself is also very stiff.
3. The runner on bowside in the bow seat has a loose piece of wood underneath (presumably to support it) which progressively works its way out from under the runner during an outing causing the seat to catch on the recovery.

**Comment by 13enedict** [comment]
I took it out this morning. The steering mechanism was OK but uses the legacy steering plate which  will probably be upgraded soon. Couldn't see any problems with the slides, besides them digging in to my legs but didn't look too closely.

I did notice that it was filthy, please make sure that you clean the inside of boats after use.
