### ISSUE TITLE
T Brackets to mount phones with the RIM app

### ISSUE THREAD

**Issue by Seb-Walker** [CityRC/Equipment#118]
Brian wants us to  collect maximum telemetry from outings this season so we can work out who really moves boats.

Can we get two T brackets as shown here http://oarsport.co.uk/product/t_bracket

I will get waterproof phone cases and we will add velcro to both so that they can be easily taken out swapped etc. (I have the velcro).

**Comment by 13enedict** [comment]
Spoke to Seb who said he now wants 4 of these

**Comment by 13enedict** [comment]
Discussed with Seb and made alternate arrangements. Cancelled the order.
