### ISSUE TITLE
Urgent - John Henry / Eddie Legg

### ISSUE THREAD

**Issue by JackLA** [CityRC/Equipment#119]
With some high urgency we need to get these boats rowable and steering well as we have a huge demand on pairs and doubles at the moment across both squads.

What we need to do on both boats is what you did with Benny's steering, (placing guide ferrules in place as well as the outer tubing on the cables).

We will also need a steering footplate for Eddie - as we do still have the original pair riggers (it was bought as pair and converted to double) - we may need a more modern one for John too - adjustable shoes in these would be fine.

Secondly we need quite a bit of steering cable for Tony, and these two pairs

If we can get an order in ASAP so this could hopefully be done by the weekend that would be great otherwise we're going to have to scratch some boats for pairs head.

**Comment by 13enedict** [comment]
The requisite parts including cable, steering plates, cable guides and pulleys should arrive tomorrow. This stuff can take quite a while to sort out, though. I'm not sure if I'll have time to refit CAM005 Eddie Legge before Saturday

**Comment by 13enedict** [comment]
CAM202 John Henry has now been upgraded to Bowden steering

**Comment by 13enedict** [comment]
CAM005 Eddie Legge has now been upgraded to Bowden steering
