### ISSUE TITLE
Brian's Shoes

### ISSUE THREAD

**Issue by manu142** [CityRC/Equipment#122]
Hi Brian,

The Shoes in Brian are quite large, and I was wondering if it would be possible to get an alternate footplate with smaller shoes (such as the small Adidas shoes, currently on the top shelf of the tools area).

Many thanks,

Garret

**Comment by 13enedict** [comment]
How are the new adjustable shoes?

**Comment by manu142** [comment]
From the row at Peterborough today, they were really comfortable! Thanks Benedict,
Kind regards,
Garret 

    On Saturday, 5 November 2016, 18:16, Benedict <notifications@github.com> wrote:
 

 How are the new adjustable shoes?—
