### ISSUE TITLE
CAM186 Jasmine Orriss footstretcher

### ISSUE THREAD

**Issue by 13enedict** [CityRC/Equipment#123]
Drop everything. The footstretcher on Jasmine has broken; a large crack along the top has opened up.

**Comment by JackLA** [comment]
OK we need Jasmin urgently for this weekend - this should be top of the
priorities list

**Comment by 13enedict** [comment]
As the single I use, it's always at the top of the priorities list

**Comment by 13enedict** [comment]
I've just spoken to Janousek, the footstretcher has to be custom made. It will take them a minimum of two weeks (no anodising) and up to three weeks (anodised) to make it. ☹️

**Comment by JackLA** [comment]
Ok how big is the crack and can we get it welded temporarily - it will be
needed this week. if not that big, I suspect that it will be able to cope
with another weeks use.

**Comment by 13enedict** [comment]
It'll need to be bent back into shape; the footstretcher has deformed around the crack but it hasn't fully separated. It might be possible to temporarily weld it back together

**Comment by JackLA** [comment]
Ok I suggest the weld, bend it as much as possible otherwise we're a bit up
shit creek for SBH

**Comment by JackLA** [comment]
Can you book It out online so people know not to use it

On 26 September 2016 at 15:35, Jack Lawlor-Anderson <jack@lawloranderson.com
> wrote:

> Ok I suggest the weld, bend it as much as possible otherwise we're a bit
> up shit creek for SBH
>

**Comment by 13enedict** [comment]
It should be welded tomorrow. The guy thinks it will only be a temporary repair but hopefully it'll at least get us through the weekend.

**Comment by JackLA** [comment]
Nice one

**Comment by 13enedict** [comment]
Jasmine is back in action! The repair is only temporary and I've placed an order for a new footstretcher.
