### ISSUE TITLE
Clippy Washers

### ISSUE THREAD

**Issue by Jess-upton** [CityRC/Equipment#128]
Can we get clippy washers on
Cranch
Benjamin
Tony
Green 2x
Angels

Plus a selection to put on the small boats

Happy to fit them once they are delivered.

Thanks

**Comment by JackLA** [comment]
There's about 50 at the back of the boathouse (blue in bags)

**Comment by Jess-upton** [comment]
Thanks - Benedict wasn't sure so said to log it on here.  Can someone let Tony know so he can put them on Benjamin next time he is out?

**Comment by 13enedict** [comment]
(these have been ordered)
