### ISSUE TITLE
Top Hole or Bottom hole?

### ISSUE THREAD

**Issue by Jess-upton** [CityRC/Equipment#129]
Can we find a way to clearly mark which hole the riggers are rigged on.  Want to avoid getting to races and people saying 'oh, were we on the top hole or the bottom hole'

Thanks
Jess

**Comment by JackLA** [comment]
We discussed at the start of the year all sweep boats the top hole (to make
the rigger lowest), the sculling boats I'm not so sure over as this depends
who is going to be using them - it's probably time to have a run round all
of the small boats and check they are on a standard rig
