### ISSUE TITLE
Please order new life jackets

### ISSUE THREAD

**Issue by ianwellwood** [CityRC/Equipment#131]
Hi,
As discussed at CCRC Committee - please order 2 new life jackets. I have spoken to some of the coxes - 
this seems the model we are after:

http://www.lifejackets.co.uk/products/472/crewsaver-crewfit-red-harness-150n-manual-pull-cord-gas-lifejacket

I don't know if you  have another supplier that you use - but this model appears the most suitable.
Please let me know when they arrive - I will mark them up and make up some training materials for coxes.
I have condemned, destroyed and disposed of 2 old unsuitable jackets.

Thanks,
Ian

**Comment by 13enedict** [comment]
These have been ordered
