### ISSUE TITLE
Steering footplate in Bejamin

### ISSUE THREAD

**Issue by JackLA** [CityRC/Equipment#138]
The plate needs replacing, where the shoes have been left loose and screws loose the footplate holes have been worn away - I would suggest we start using "lock tight" on the shoes/footplates to avoid this - it's a common theme that users of the equipment don't tighten the shoes up if they find them loose.

**Comment by 13enedict** [comment]
Yeah, I've been meaning to get some Threadlocker (which I assume you mean).

**Comment by NSinclair94** [comment]
I am closing down all old issues. If this still hasn't been fixed, please raise a new issue.
