### ISSUE TITLE
Laurie race number slot

### ISSUE THREAD

**Issue by Jess-upton** [CityRC/Equipment#143]
Hi,

Laurie doesn't have a race number slot - please let me know if we have one and I can fit.

Thanks
Jess

**Comment by 13enedict** [comment]
We do, I was going to fit it the other day but it was being used. It’ll need to glued as the holes are worn from people breaking the slots off so many times. 🙄

**Comment by 13enedict** [comment]
Glued a new one on

**Comment by Jess-upton** [comment]
Hi, This needs to be reopened 

I have currently used Duct tape to secure a race slot as we needed one for Rutherford.  New holes need drilling in order for screws to fix properly (or the current wholes need filling).  Let me know if anything I can do to help on this one.
Jess

**Comment by 13enedict** [comment]
Janousek recommends filling the holes in. They use resin with glass
bubbles. I don't think that we have any resin but I'll have a look at what
we do have.

**Comment by Jess-upton** [comment]
Hi, Just another update.  The race slot is currently held on with Duct tape.  Are we able to do a better repair?

**Comment by NSinclair94** [comment]
I am closing down all old issues. If this still hasn't been fixed, please raise a new issue.
