### ISSUE TITLE
Re-arming kits CO2 + clip for life jackets

### ISSUE THREAD

**Issue by ianwellwood** [CityRC/Equipment#146]
Hi Benedict,
Please can we order 2 re-arming kits for life jackets. United Moulders Manual Rearming Kit 33g (12.99 pounds). I am pretty sure these will fit (feel free to use another supplier if you can find a better deal)

http://www.lifejackets.co.uk/products/103/united-moulders-manual-rearming-kit-33g

Once they arrive - just let me know and I can fit them and recommission the jackets.
Thanks

**Comment by 13enedict** [comment]
These have been ordered.
