### ISSUE TITLE
Brian - Shoes

### ISSUE THREAD

**Issue by CCRCJuniors** [CityRC/Equipment#147]
Hello

The shoes in Brian are quite small, I suspect they may have been changed by one of the jnr boys, but they are too small for some of the other boys who are using it.  Is there another larger pair that we could replace them with or use to swap in/out?  The other 2 boys using it are size 12/13.
I can change them over at the weekend, just need to know where to find shoes.

Thanks
Tammy

**Comment by 13enedict** [comment]
Boat now has some 6 - 10 size which should cover a decent range of users. Is this suitable?

**Comment by CCRCJuniors** [comment]
Perfect.
