### ISSUE TITLE
The Natural. Loose footplate in bow's seat

### ISSUE THREAD

**Issue by Karlovik** [CityRC/Equipment#159]
Hi,

The footplate in bow's seat is very  wobbly. During the outing a couple of screws came off the left shoe and the shoe came off. We put them back in but not very tightly since we couldn't find a screwdriver. The right shoe only has one screw which makes it move from side to side. 

Thanks, 

Carlos

**Comment by 13enedict** [comment]
I assume this has already been fixed, please reopen if not
