### ISSUE TITLE
Doreen 

### ISSUE THREAD

**Issue by shannonbjt** [CityRC/Equipment#160]
Hi B,
2 small issues with Doreen:
1. Stroke - screw loose on foot plate so lifting at bottom
2. 4 - shoes lifting as missing piece of metal on wing nut 
May I add that I don't sit in either seat and have been asked to report these issues, so don't shoot the messenger. 
Happy Xmas 
Bernie

**Comment by 13enedict** [comment]
Refitted foot plate track to the wooden holder. This may not be a long term solution as it was a bit rotten
