### ISSUE TITLE
Rupert

### ISSUE THREAD

**Issue by colmcmurphy** [CityRC/Equipment#161]
Left shoe is not fully connected to the footplate. Two screws are missing, both on the left hand side . As such, steering isn't as efficient and there is a risk that the shoe could detach entirely from the footplate.

As Rupert is being used in the Winter League over the weekend, is it possible to fix this quickly please? I can come down to help if needed.

**Comment by 13enedict** [comment]
If footplate screws come loose, we do actually have some Threadlocker in the cupboard at the front to keep them in. I'm going to assume this has been tightened. Please reopen if it's still a problem :)

**Comment by colmcmurphy** [comment]
I corrected myself.
