### ISSUE TITLE
Benjamin

### ISSUE THREAD

**Issue by colmcmurphy** [CityRC/Equipment#162]
The bow seat left shoe detached from the footplate during the Winter league racing.

The shoe is still in attached to the footplate by the heel restraints but the plate and corresponding screws used to connect the front end of the shoe to the footplate detached. 

I have left the plate on the work bench.

**Comment by 13enedict** [comment]
Do you literally mean, the screws have come undone??

**Comment by colmcmurphy** [comment]
I think so - the plate connecting the front end of the left shoe to the footplate separated completely. I could only find one screw in the boat afterwards, which I left next to the plate on the work bench.

I realised the connecting plate was loose on the way down to the start line but by then it was too late to correct. It felt like there was only one or two screws connected instead of the standard four. As the boat is the top men's 4- racing boat, I wanted to raise the issue instead of correcting myself (and risking the possibility of getting blamed on race day for not correcting properly).
