### ISSUE TITLE
Erg chain needs some maintenance (is marked as broken)

### ISSUE THREAD

**Issue by francescaaxe** [CityRC/Equipment#163]

**Comment by JackLA** [comment]
When you say it's marked as Broken? Is it one of the new three or old one?

**Comment by francescaaxe** [comment]
Hi,
I meant I've put a note on it saying it's broken so it can be identified.

**Comment by francescaaxe** [comment]
It's one of the newer ones

**Comment by 13enedict** [comment]
Fixed by JLA
