### ISSUE TITLE
Cranch 6 speaker

### ISSUE THREAD

**Issue by Jess-upton** [CityRC/Equipment#165]
girls have reported 6 speaker isn't working - can we look at the wiring?

**Comment by Jess-upton** [comment]
Hi,
Just to say this is still not working properly - we can manage (as they are close enough to the cox to hear) but we do need it fixed before bumps - please let me know who I should ask to look at it and I'll get in on trestles.
Jess

**Comment by Jess-upton** [comment]
Hi Benedict, Still having issues with the 6 speaker in Cranch - do we have a spare I could plug in to see if it is the speaker or something more complicated.

**Comment by 13enedict** [comment]
We have at least one spare but we should have a few
