### ISSUE TITLE
Slides for Tailwind

### ISSUE THREAD

**Issue by CCRCJuniors** [CityRC/Equipment#167]
Tailwind

Tailwind requires new slides.  I have been ensuring that M2 clean the slides and wheels after the outings but they are very pitted through wear and tear/lack of care.  I will personally take responsibility for ensuring they are cleaned after each M2 outing and I am sure we can have a word with the Presidents 8 who are the other main user of this boat.
All seats are affected.  We might need to look at the wheels on some of the seats too ... I will take a look on Saturday.

Thanks!

Tammy

**Comment by JackLA** [comment]
We should have some Filippi slides at the back of the boathouse. Tailwind's
slides are 5 years old now so probably due for a replacement.
