### ISSUE TITLE
Redeham&Weep shoes at 5 seat

### ISSUE THREAD

**Issue by CCRCJuniors** [CityRC/Equipment#169]
Redeham&Weep

Footplate at the 5 seat has jammed.  Reported by Sue Brown from St Mary's.  They tried to fix it but the nut has threaded and is now jammed.  Any change it can be fixed by Fri lunchtime?

I somehow have managed to assume the position of boat repairs secretary, but this will end, now!

**Comment by 13enedict** [comment]
I'm away at the moment - I can't guarantee I'll be back to fix this - can they not use Wholly?

**Comment by 13enedict** [comment]
Also, yes, boat repairs are miserable
