### ISSUE TITLE
Holes in CAM321 Redeham and Weep

### ISSUE THREAD

**Issue by umarndt** [CityRC/Equipment#17]
As posted in the gate issue (duplicate to appease Ben ;) 

-holes on side of Reedham, not leaking
-holes underneath Stroke seat
-hole besides seat 3
-potential other smaller holes, need fixing (when it's dry outside)

**Comment by 13enedict** [comment]
Just be glad I'm not insisting each hole is a separate issue 🙈

**Comment by JackLA** [comment]
Perhaps we swap Laurie and Reedham on Saturday, I can show Rob how to fix holes on Sunday and use Reedham to do so

**Comment by umarndt** [comment]
Redeham is good to race and we trained in it, I wouldn't want to swap boats
unless absolutely necessary

**Comment by JackLA** [comment]
I meant after racing..... so it's on a rack inside Saturday night, then it's dry and I can work on it

**Comment by 13enedict** [comment]
Sounds good. @umarndt can you and Laura arrange the boat swap.

**Comment by umarndt** [comment]
no problem
