### ISSUE TITLE
Laurie 

### ISSUE THREAD

**Issue by AmandaButtery** [CityRC/Equipment#174]

**Comment by JackLA** [comment]
Hi all, this is most likely because the section hasn't been done up
properly. Some Vaseline between the join and a re tightened should solve it

**Comment by 13enedict** [comment]
Is the leak coming in where the boat is joined? There should be an
athwartship bulkhead to prevent that. In any case, I would guess, most
likely that the boat was improperly joined.

**Comment by AmandaButtery** [comment]
Thanks both. Yep. The leak is coming in where the boat is joined. It was first notice by cox at Norwich that stroke side of join seemed to have a larger gap than bow side. Foot well filled quite a lot with water on Thames on Saturday (just at 4) and then was taking a closer look on Sunday. Will try and organise with crew to do as you suggest Jack with the Vaseline and re tighten before next outing. Hopefully that will do the trick.

**Comment by 13enedict** [comment]
If you were to put a gun to my head: I doubt that this is vaseline related; it hasn’t been joined properly. There’s no reason for there to be a gap unless 1) something is obstructing it, or 2) it hasn’t been tightened up properly (or 3) the boat is some how warped and I doubt it). Also, I don’t think that this is a problem on this shell, but check that both the nuts AND the bolts are tight

**Comment by JackLA** [comment]
All joins should have Vaseline between the join regardless

**Comment by 13enedict** [comment]
Ok, someone needs to show me this as there are compartments either side of the join
