### ISSUE TITLE
Liberty rigger broke

### ISSUE THREAD

**Issue by Git-Oryx** [CityRC/Equipment#175]
Liberty
3's Wing rigger broken

![img_6979](https://cloud.githubusercontent.com/assets/3437886/23917391/1589b19a-08e7-11e7-80eb-d73838a230f4.JPG)

**Comment by 13enedict** [comment]
Gosh. How did it happen?

**Comment by Git-Oryx** [comment]
Apparently was crushed up against the bank when an VIII+ squashed them along side the bank!?

**Comment by Git-Oryx** [comment]
Please let myself or Tammy know when we can expect it back in order, thanks.

**Comment by Jess-upton** [comment]
Hi, any idea when we will be able to get Liberty back in action as a 4x?  Happy to rig as 4- in the mean time (I just need to get round to doing that!)

**Comment by Jess-upton** [comment]
Do we have a delivery date for this?  It has been out of action for a while now.

**Comment by 13enedict** [comment]
The new rigger is being made by the supplier

**Comment by NSinclair94** [comment]
New rigger has been installed with help from Colm. First crew out in it may want to take time to adjust the rigger height and span.
