### ISSUE TITLE
'Ralf' M4+ CAM400 

### ISSUE THREAD

**Issue by shannonbjt** [CityRC/Equipment#176]
'Ralf' M4+ CAM400 

No 2 rigger bent and crack in shell after capsize 

No 2 

None

**Comment by 13enedict** [comment]
I really hope that this is a joke

**Comment by shannonbjt** [comment]
Unfortunately not Benedict,


No 2 blade hit the bed of the river which led the rigger to bend under the strain.


And yes I do know they had all just been replaced.


Bernie

**Comment by 13enedict** [comment]
![image](https://media.giphy.com/media/OBuQCM5IlgGs/giphy.gif)

**Comment by shannonbjt** [comment]
😞

Sent from my Windows Phone
________________________________

**Comment by 13enedict** [comment]
Janousek have quoted £2100 for repairs, I'm getting a second opinion
tomorrow

**Comment by JackLA** [comment]
PC boat repairs?

**Comment by 13enedict** [comment]
They're the ones looking tomorrow

**Comment by JackLA** [comment]
OK excellent he's very good and good value for money - Might as well get a
quote for Janet May Silk, Natural and Lwt Goat for refurb while he's there.
Lwt goat leaks quite badly, Janet is a pig to row and the natural
desperately needs some work

**Comment by 13enedict** [comment]
I hope you're right because the Janousek quote was even higher than I
expected however, they were cheaper than PC on other quotes I've had

**Comment by JackLA** [comment]
We shall see - have we got a new rigger on the way for Liberty?

**Comment by 13enedict** [comment]
Boat is being picked up next week for 5 week repairs

**Comment by Jess-upton** [comment]
Ralf is repaired
