### ISSUE TITLE
Bushes needed for Laurie

### ISSUE THREAD

**Issue by JackLA** [CityRC/Equipment#180]
Doreen

Needs spare bushes ordered for sax boards.

**Comment by 13enedict** [comment]
We have a bunch of these, I believe. I'm not sure if they've been fitted but we'd need to remove the riggers to fit them. Also, there has been a bad habit of removing the (expensive) bushes so I suggested gluing them in place.

**Comment by bjarr21** [comment]
Need to revisit this again.  Laurie is losing bushes.

**Comment by 13enedict** [comment]
Pretty sure we have bushes but need boat to be derigged, then bushes glued in place

**Comment by bjarr21** [comment]
Happy to organize a day to do this.  Or can it be done in conjunction with Peterborough or Oxford?
