### ISSUE TITLE
Hilary - Broken Rigger

### ISSUE THREAD

**Issue by CCRCJuniors** [CityRC/Equipment#182]
Hilary

Left (bowside) rigger has sheared, looks like the point where the previous crack was welded. Needs a new rigger, doesn't look like it can be welded.

**Comment by 13enedict** [comment]
I think that this boat has Len Neville riggers which probably means we'd need to replace both. 
This maybe means that we should consider whether the shell is worth repairing, @JackLA?

**Comment by 13enedict** [comment]
Sorry, I mean replacing

**Comment by Terywall** [comment]
I'm afraid that I broke Hilary (left bowside rigger) on Saturday morning - although saddened to hear that it was a previously 'welded part' that broke.  All this time, I've been quietly pleased with my non-existent machoness.... :-(

**Comment by NSinclair94** [comment]
New rigger coming
