### ISSUE TITLE
Scratch on Doreen's shell

### ISSUE THREAD

**Issue by Karlovik** [CityRC/Equipment#187]
### Scratched shell and broken bowball

After 99's regatta, when we were parking, we mounted the bow on the bank scratching the bottom of the boat. It´s quite straightforward to see the scratch.

Moreover the bowball is broken, but I guess that´s easy to replace. Reporting, anyway.

Cheers,
Carlos

**Comment by 13enedict** [comment]
How did this happen??? Have you got a photo?

**Comment by umarndt** [comment]
There was already a rather deep scratch covered by green tape but the Cox
was too fast while landing the boat. :(

**Comment by Karlovik** [comment]
![14961277569441161208974](https://cloud.githubusercontent.com/assets/10038426/26571563/68a2e46a-450e-11e7-9927-bb70cddee30b.jpg)
![1496127792843623970669](https://cloud.githubusercontent.com/assets/10038426/26571576/7ac2225a-450e-11e7-9464-08da13f5a1ce.jpg)
Hi @13enedict 
Here they are. Seb suggested to put some tape on temporarily.

**Comment by 13enedict** [comment]
If this is your idea of a scratch, I  dread to think what real damage would
look like. It will have to go away.

**Comment by hawkxro** [comment]
tbh, it didn't look that bad the last time I had a look at it. How long do you think it will take to fix it? Since you're at it, can you have a look also at the magnet under the stroke seat? There is something wrong with it as the rate-meter doesn't work properly.

Thanks a lot
Claudio

**Comment by NSinclair94** [comment]
I am closing down all old issues. If this still hasn't been fixed, please raise a new issue.
