### ISSUE TITLE
Sharp Screw on Wholly - Seat #7 CAUSE of RECENT INJURY - Please adjust / make safe

### ISSUE THREAD

**Issue by ianwellwood** [CityRC/Equipment#188]

**Comment by 13enedict** [comment]
I had a look at the boat, there are the usual bolts protruding from the shell for when it is bow rigged. This is pretty standard practice so I would suggest raising it at the committee meeting to figure out what to do.

**Comment by ianwellwood** [comment]
Dear Benedict,

Thanks for checking and considering options. Agree taht it can be raised at the Committee to see if anyone has solution / suggestions.

Regards,

Ian



________________________________

**Comment by JackLA** [comment]
I had a look too... it's just normal bolts that any boat in the club has...
I'm not sure how on earth they managed to do it....
