### ISSUE TITLE
Wholly- Shoes in DIRE need of replacement

### ISSUE THREAD

**Issue by bjarr21** [CityRC/Equipment#190]
Wholly
Shoes in Bow, 5, 6, 7, and Stroke are all shot.  Especially 6 and stroke.  6 blew out during the race last night.
Requires duct tape to hold your feet in

**Comment by 13enedict** [comment]
What do you mean by shot?

**Comment by bjarr21** [comment]
completely blown out

**Comment by 13enedict** [comment]
Ok and what does blown out mean in the context of shoes?

**Comment by bjarr21** [comment]
Several were not staying closed- the velcro is not holding, so there is
nothing to keep you in the shoes.  And 6 is the one that she said ripped
out- I understood that it came off the footplate.
