### ISSUE TITLE
John Henry missing stroke seat footplate

### ISSUE THREAD

**Issue by Seb-Walker** [CityRC/Equipment#191]
Eddie Legg was found to be missing its stroke seat foot stretcher.  I therefore swapped it with John Henry's as John Henry is used less often.  John Henry is now being used for York Regatta.  I'm logging it here, but perhaps we can sort it this Tuesday.

**Comment by 13enedict** [comment]
The footplate is inside the boat bay door. I suspect that @CCRCJuniors might be involved, as Tammy was doing something with it...
