### ISSUE TITLE
Olive- Shoe off of footplate

### ISSUE THREAD

**Issue by bjarr21** [CityRC/Equipment#199]
### Boat name or ID
Olive
### Problem description
Left shoe came off footplate
### Seat number(s) affected
2

**Comment by NSinclair94** [comment]
Where is olive? I can have a look tonight.

**Comment by bjarr21** [comment]
Might need to check with Colm- I believe he said they fixed it on the
boathouse day?  But it is on the side of City

**Comment by 13enedict** [comment]
@colmcmurphy ?

**Comment by colmcmurphy** [comment]
I've checked with the girls who were at the spring cleaning last Saturday - Olive wasn't looked at then so the issue still needs fixing. 

Olive is outside on the trinity side on the racks  behind the singles.

If people can get down to City earlier this evening (say 6pm?), we can lift onto trestles and screw in the left shoe quickly.

**Comment by NSinclair94** [comment]
@colmcmurphy I am happy to give you a hand, but in future we should try to promote this kind of thing being done at the start/end of outings as it takes 5 minutes

**Comment by colmcmurphy** [comment]
Agreed.
