### ISSUE TITLE
Eddie Legge and John Henry Sharp Slides

### ISSUE THREAD

**Issue by graeham** [CityRC/Equipment#201]
### Boat name or ID
Eddie Legge and John Henry
### Problem description
Sharp areas around the slides cause cuts to calves of rowers. Suggest taping and/or filing sharp edges. 
### Seat number(s) affected
All

**Comment by 13enedict** [comment]
These just need to be filed down at the front, on the bottom - I already
did on one of the stroke seats (probably Eddie Legge) when I was EO and I
forgot to bring leggings to Peterborough Regatta

**Comment by NSinclair94** [comment]
Will be fixed when refurbished
