### ISSUE TITLE
M2 Blades Grips To Install

### ISSUE THREAD

**Issue by graeham** [CityRC/Equipment#202]
### Boat name or ID
M2 Blades
### Problem description
Some grips are distroyed. New grips in the first aid box at the front of the boat house. Consider full replacement of all M2 grips. Some M1 blades could also use a replacement.

**Comment by 13enedict** [comment]
From memory, this is easy to do - just unscrew the end and it pops off. Otherwise, it might be glued on

**Comment by graeham** [comment]
@13enedict yep - looked like one screw in the inboard end and a screw/bolt forming a close at the end towards the blade.

**Comment by NSinclair94** [comment]
Swapped most over, kept the old ones as spares
