### ISSUE TITLE
Audio is a mess

### ISSUE THREAD

**Issue by 13enedict** [CityRC/Equipment#203]
### Boat name or ID
CAM400 Ralf

### Problem description
There are two sets of speakers fitted at the moment, the original loom which has a loose connection somewhere and another separate loom with just one speaker attached and is poorly fitted onto the deck and isn't working. I would suggest fixing the original audio (happy to help) and removing the other loom.

**Comment by graeham** [comment]
IIRC this was a hack fix before Oxford Regatta, where the original cable had been epoxied through the bulkhead. Looked like it would need to be drilled out?

**Comment by 13enedict** [comment]
Yeah, some boats are a pain in this respect but hopefully, the cable can be
fixed in situ.

**Comment by 13enedict** [comment]
Fixed audio and fitted second speaker.
