### ISSUE TITLE
Doreen bow's adjuster strip

### ISSUE THREAD

**Issue by Karlovik** [CityRC/Equipment#204]
### Problem description
It's not really the footblade. It's the thing where the footblade is screwed to the boat. Let's call it bottom footblade railings.
Essentially they are loose. The holes where that is screwed to the boat are too wide so it can't be screwed back. Right now is taped.

I hope to take some pictures soon because this explanation is horrendous.

**Comment by 13enedict** [comment]
What is a footblade?

**Comment by NSinclair94** [comment]
My guess is the screw's holding the nogged channel have stripped away the threading. I would imagine it would just be filling the hole with resin and then redoing the thread?

**Comment by umarndt** [comment]
Probably a footplate XD

**Comment by Karlovik** [comment]
I don't know, Benedict. It is just the word I came up with yesterday night because I was too tired to care about orthography (if that even qualifies as an orthographic error) but not so tired to keep postponing raising the issue.
Yes, I believe what Nick says is about right.

**Comment by 13enedict** [comment]
Assuming we're talking about the adjuster strips, onto which the foot stretchers fit (not foot plates, they're a different thing), the middle ones are usually screwed into wood - it may be that the wood has rotted away which would mean getting some new wood, painting it and (I think) gluing it in. Might be worth talking to Janousek for their advice.

**Comment by Karlovik** [comment]
![img_20170922_165721](https://user-images.githubusercontent.com/10038426/30754441-95f4a730-9fba-11e7-8fec-4c55b69c725b.jpg)
![img_20170922_165638](https://user-images.githubusercontent.com/10038426/30754440-95f17dee-9fba-11e7-9426-a208fd7bffe1.jpg)
![img_20170922_165723](https://user-images.githubusercontent.com/10038426/30754439-95ed958a-9fba-11e7-9b6b-df86c1ca2caf.jpg)

Hopefully these pictures help. Apparently, the screws that are shown in the picture don´t screw as the hole they are supposed to go in is worn out

**Comment by 13enedict** [comment]
Would suggest that you move it up or down a notch and screw it into the fresh wood there

**Comment by 13enedict** [comment]
Assuming that this has been fixed. Pls reopen is not
