### ISSUE TITLE
Unsafe bow ball

### ISSUE THREAD

**Issue by 13enedict** [CityRC/Equipment#205]
### Boat name or ID

CAM800 Laurie Halifax 

### Problem description

The bowball is unsafe, it's attached on one side but not the other and in a collision, it's quite likely to impale someone

**Comment by colmcmurphy** [comment]
How did this happen?

**Comment by 13enedict** [comment]
I couldn't say- I just noticed it after your highlighted it to me

**Comment by NSinclair94** [comment]
Done, with the help of the women's captain.
