### ISSUE TITLE
Boat registration stickers

### ISSUE THREAD

**Issue by 13enedict** [CityRC/Equipment#206]
Put them on the boats; the previous equipment officer, although a fine chap, did not finish putting them on for this year.

**Comment by NSinclair94** [comment]
@13enedict i have applied stickers to all the appropriate boats, however there are still some boats without stickers and some stickers without boats

**Comment by 13enedict** [comment]
The Salanis won't have stickers. Check out the [fleet page](https://github.com/CityRC/Equipment/wiki/Fleet) to see private boats - they need to pay us back for their registrations.
