### ISSUE TITLE
Ultra splash guard broken after collision with Tabs double

### ISSUE THREAD

**Issue by gdg23** [CityRC/Equipment#222]
### Boat name or ID
Ultra

### Problem description
Bow seat splash guard broken almost completely off. Doesn't affect rowability but means water can get into honeycomb of shell and into bow section so I would have thought best to take out of action til fixed.

### Seat number(s) affected
Bow

### Photos of the issue
Sorry didn't get any

**Comment by NSinclair94** [comment]
Could you please write a report and send it to the safety officer or myself

**Comment by gdg23** [comment]
This is what Andrea sent to Benedict:"While out in the pair this morning, we had an accident with a Cantabs double (boat name Lizzie) which was on the wrong side of the river between Chesterton bridge and the car park in Chesterton. We were going downstream.I hit their bow person in the back with my stroke side blade and they damaged Ultra’s splash guard with their bow side blade. Ultra is now damaged, and water can potentially go into the watertight compartment under rain or if water pours into the boat.We put the do not use tag on the oar lock.Cantabs are filing an incident report for the insurance, but we should file one too.Can you please let us know how we can support filing the report?"Is that ok?GuyOn 12 Nov 2017 2:03 p.m., NSinclair94 <notifications@github.com> wrote:Could you please write a report and send it to the safety officer or myself

**Comment by NSinclair94** [comment]
Benedict has already forwarded this on to me, I will pass it on to Ian

**Comment by gdg23** [comment]
Ok thanksOn 12 Nov 2017 3:01 p.m., NSinclair94 <notifications@github.com> wrote:Benedict has already forwarded this on to me, I will pass it on to Ian

**Comment by 13enedict** [comment]
I think that this has been fixed; are we billing Cantabs?

**Comment by gdg23** [comment]
Yes this should absolutely be billed to Tabs

On Tue, 23 Jan 2018, Benedict wrote:

|
|I think that this has been fixed; are we billing Cantabs?
|
|—
|You are receiving this because you authored the thread.
|Reply to this email directly, view it on GitHub, or mute the thread.[ARUBGg2GOqfbV316DUNSn86Nb2KxJFa-ks5tNeeUgaJpZM4Qa2k4.gif]
|
|
|

--

Guy Goodrick
Network Systems
University Information Services
Roger Needham Building
7 JJ Thomson Avenue
Cambridge
CB3 0RB

(01223) (7)63485
www.uis.cam.ac.uk

**Comment by NSinclair94** [comment]
I believe we are currently trying to get money off them
