### ISSUE TITLE
Kieran West audio not working

### ISSUE THREAD

**Issue by 13enedict** [CityRC/Equipment#226]
### Boat name or ID
CAM012 Kieran West
### Problem description
Audio wiring is not working. On trying a CoxBox, there was no audio, after isolating speakers, it _looks_ like at least two separate sections of the loom weren't working.

**Comment by NSinclair94** [comment]
We did it Benedict

**Comment by 13enedict** [comment]
Fitted new wiring loom, including one new module M and one used module M. Two speakers needed to be replaced
