### ISSUE TITLE
W3 Blade

### ISSUE THREAD

**Issue by colmcmurphy** [CityRC/Equipment#229]
One of the W3 blades (former St Mary's) was damaged during Winter League I.

It is currently stored at the back of the boathouse near the equipment desk.

The collar detached and the blade colour (white coloured blades) has peeled off.

**Comment by colmcmurphy** [comment]
Can we fix this? I can help some evening this week (just need to be told what to do).

**Comment by NSinclair94** [comment]
I have replaced the collar, it just needed tightening. I don't fully understand what you mean when you say the colour has peeled off

**Comment by colmcmurphy** [comment]
Thank you. I took a look this evening and everything seems to be in order. The report I had from the women was that the paintwork had come off but on inspection this evening, only a small portion had.
