### ISSUE TITLE
Cranch Steering, Paintwork and Speaker

### ISSUE THREAD

**Issue by colmcmurphy** [CityRC/Equipment#230]
Several issues with Cranch:

1. The speaker at the 4 seat is not functioning. Middle four do not hear any coxing audio.

2. The rudder has a strong stroke side bias. Can we reset to make bow side a bit sharper?

3. The paintwork at the bow end of the boat was damaged during Winter League I. A small section needs to be repainted.

I can arrange for the women to place onto trestles some day. How about this Saturday after Division 1?

**Comment by 13enedict** [comment]
I can have a look around 12 on Saturday, will need to be on trestles for approx 1-2 hours.

**Comment by colmcmurphy** [comment]
Just following up on this::
4 seat speaker not working again. We think it's the wiring.

Seb has requested the paintwork be completed asap. Can we either pencil in a time to do this please? This Saturday at 11am would work well (I can help). Or can we approach a boatman?

**Comment by NSinclair94** [comment]
Why does the paintwork need to be done so urgently?
As for the speaker, I can have a look at the weekend

**Comment by 13enedict** [comment]
The paintwork is purely cosmetic and not a priority

**Comment by colmcmurphy** [comment]
Having spoken with Seb, the paintwork is cosmetic yes, but the wider view is that Cranch is the women's first boat and from a perspective (branding development dare I say) view, the club wants to give a good impression at regattas and head races. As crews will be heading to Bedford, Norwich and the Tideway soon, it would be good to have a nice looking boat that will help attract people to the club and not have people say/think "City don't look after their top boats; they're not a club I wish to join".

I can arrange for Cranch to be on trestles at 11am on Saturday. If both are you are able to help out/show me what to do, well and good. If not, then I am out of weekends to get this fixed and will have to ask a boatman.

**Comment by NSinclair94** [comment]
Just to confirm, cranch will be on trestles at 11? I will be going to get my mop chopped after the m2 outing, so when that's done I'll come back and sort the steering and speaker system

**Comment by colmcmurphy** [comment]
Thank you - the women’s outing is from 9-11. I expect to be back by 11 or a few mins beforehand.

**Comment by 13enedict** [comment]
Replaced 1 faulty speaker and fitted 1 missing speaker
