### ISSUE TITLE
Heightened Seats

### ISSUE THREAD

**Issue by colmcmurphy** [CityRC/Equipment#231]
Gytha has requested two heightened seats to help Jess Hasken and Louise with rowing.

**Comment by 13enedict** [comment]
we have the parts to assemble some wooden seats which could include some extra height

**Comment by colmcmurphy** [comment]
Gytha has been pressing this issue again this weekend. Is it something we are likely to be able to do soon?

**Comment by 13enedict** [comment]
OK, so I would like to take a step back on this. Having separate seats is something that I'm not very keen on. The first reason is that seats are expensive and the decision to get into a situation where we have a policy of this in a general sense would need to be taken by the FGPC.

I am not very keen on the routine removal and insertion of seats from boats; I fear that it will lead to seats getting lost. I also fear that the actual end result will be a random selection of elevated seats appearing in the fleet.

Prior to this going ahead, I would like to see a plan for how these seats are managed.

In addition, I would like to see what consideration has been given to alternative option, e.g. seat pads, and what advantages/disadvantages those options have.

**Comment by colmcmurphy** [comment]
Louise has confirmed she is happy with a seat pad. I'll speak to Jess at the weekend. I don't think the club should finance seat pads. They should be up to individual rowers to purchase.

**Comment by NSinclair94** [comment]
Given that Jess is leaving in a few months, I don't think there is any value in sorting a seat out.
