### ISSUE TITLE
Laurie Bowball

### ISSUE THREAD

**Issue by colmcmurphy** [CityRC/Equipment#232]
Laurie's bow ball keeps detaching. I think this is because the current one is a smaller size. Can we order one of the larger sized bow balls please and fit when received?

**Comment by 13enedict** [comment]
Fitting a larger bow ball is a bad idea; we're really only using the 2k bow balls which are more expensive and only come in one size but much stronger. It may be that Laurie's bow needs to be rebuilt 🙄

**Comment by colmcmurphy** [comment]
Can we make sure that the current one is fitted on properly again so? Laurie will be heading to Bedford and WeHoRR and School's Head and I do not want a BR umpire to prevent a crew from racing due to a loose bow ball? I'm happy to help at some convenient time.

**Comment by 13enedict** [comment]
To be clear, if the bowball isn't attached properly, the boat **must not** be used at all. Can you confirm whether the bowball is currently properly attached?

**Comment by colmcmurphy** [comment]
To confirm, the bow ball is attached. One side is fully attached, the other keeps coming loose and needs to be regularly tightened. We've also put some electrical tape around the affected side to provide further support. As discusses, the long-term issue is the shell's boat needs to be reconstructed. I would suggest from August onwards.

**Comment by NSinclair94** [comment]
Fixed
