### ISSUE TITLE
Hilary's new riggers don't fit :(

### ISSUE THREAD

**Issue by 13enedict** [CityRC/Equipment#235]
### Boat name or ID
CAM186 Hilary

### Problem description
The new riggers for Hilar appear to be made at the wrong angle - my guess is that they're about five degrees too high.

### Photos of the issue
Forgot to take one

**Comment by NSinclair94** [comment]
Shit

**Comment by NSinclair94** [comment]
Do we send them back for them to make adjustments?

**Comment by NSinclair94** [comment]
Have been received by Neaves with janousek measurements
