### ISSUE TITLE
Laurie damage

### ISSUE THREAD

**Issue by LHBailey** [CityRC/Equipment#238]
After being hit against a lamp post Laurie now has a grey mark down the stern. Not sure on the extent of the damage. Also the audio has had a quick fix but needs redoing altogether.

**Comment by 13enedict** [comment]
Ideally, these would be in two separate issues.

**Comment by 13enedict** [comment]
This issue really needs more detail; photos of the damage and log the audio separately.

**Comment by 13enedict** [comment]
Audio has been repaired, by coincidence

**Comment by 13enedict** [comment]
I am assuming that there isn't a problem here. Pls reopen is there is
