### ISSUE TITLE
Brian - shell coming away from decking

### ISSUE THREAD

**Issue by NSinclair94** [CityRC/Equipment#242]
The shell is coming away from the decking, will need to go to Tim rhodes

**Comment by 13enedict** [comment]
Is this in addition to the shoulder breaking?

**Comment by NSinclair94** [comment]
This has been sent to Tim, I will make him aware of the weakness in the shoulders in the boat.
Whilst this is away, should a boat be moved to the CRA in place of brian so that we don't lose the space?

**Comment by 13enedict** [comment]
How long will it be away?

**Comment by NSinclair94** [comment]
Back by the weekend I reckon

**Comment by NSinclair94** [comment]
It was noticed that this is starting to peel away again on training camp?

**Comment by NSinclair94** [comment]
Done for now, when it becomes a problem again it will have to be taken to Tim Rhodes.
