### ISSUE TITLE
Pindoulette

### ISSUE THREAD

**Issue by NSinclair94** [CityRC/Equipment#244]
Right rigger on pindo has sheared off, previous fix has broken again. Middle stay of rigger is also peeling away from the shell.
Would recommend backstays fitted when fixed.

**Comment by 13enedict** [comment]
I don't think it can take backstays

**Comment by NSinclair94** [comment]
This has been sent to Tim. You are right in saying that it can't take backstays.

**Comment by NSinclair94** [comment]
All done, I will close this until it happens again
