### ISSUE TITLE
Rolling bearings on the seat on 🐐

### ISSUE THREAD

**Issue by 13enedict** [CityRC/Equipment#248]
### Boat name or ID
CAM121 Lwt City Goat

### Problem description
The rolling bearings inside the wheels in the seat have failed, at least one catastrophically.

Do we have any spare wheels?

**Comment by NSinclair94** [comment]
There are plenty of spare seats at the back of the boathouse, I would imagine at least one will fit

**Comment by 13enedict** [comment]
Replaced the wheels on the seat
