### ISSUE TITLE
Rudder Doreen

### ISSUE THREAD

**Issue by eyalpole** [CityRC/Equipment#252]
### Cox (Jessica) complained about steering problems - the rudder jerking at one point

**Comment by NSinclair94** [comment]
Is the cable still attached?

**Comment by eyalpole** [comment]
Yes.  The cox complained that is is just difficult to steer (jerks after a certain point).  
    On Monday, 23 April 2018, 11:35:07 BST, NSinclair94 <notifications@github.com> wrote:  
 
 
Is the cable still attached?

**Comment by 13enedict** [comment]
That doesn't make a lot of sense, unless it's bent, maybe? I'd just
straighten it up.

The only other things I can think are plausible are the yoke being on
backwards, allowing it to over-steer, or the cable being frayed and getting
caught on the loops.

More info would be handy 👍

**Comment by NSinclair94** [comment]
So it just sounds as if there is little librication. Could you spray some WD-40 on both ends of the rudder.
It may be difficult to steer if too much rudder is being used, it should be ~25° max otherwise it starts acting as a brake

**Comment by NSinclair94** [comment]
Steering mechanism just needed oiling. In future can you make that your first port of call.
