### ISSUE TITLE
Broken foot plate 

### ISSUE THREAD

**Issue by Emilyhogg** [CityRC/Equipment#259]
Redeham 

Foot plate nut has snapped off 

Seat 5

**Comment by NSinclair94** [comment]
Thank you for raising this. When are you next out in the boat, as I have been made aware that it wasn't washed before it was put away

**Comment by Emilyhogg** [comment]
We are out in the boat again Saturday at 9am.

**Comment by hawkxro** [comment]
that was my decision, sorry 
will wash it properly after the outing tomorrow morning

**Comment by NSinclair94** [comment]
Thank you, I will sort something this evening.

**Comment by NSinclair94** [comment]
Please close this issue when it has been fitted back onto reedham

**Comment by NSinclair94** [comment]
Footplate is on back bench, will need shoes attached
