### ISSUE TITLE
Broken Collar on M3 Oar

### ISSUE THREAD

**Issue by eyalpole** [CityRC/Equipment#260]
Broken Collar on M3 bow-side Oar.

**Comment by NSinclair94** [comment]
When I go through and fix these, someone from m3 will have to be in attendance to learn how to fix the cost and gate

**Comment by 13enedict** [comment]
...nice!

**Comment by eyalpole** [comment]
Ok.  When do you want to do this?
    On Sunday, 20 May 2018, 16:29:40 BST, NSinclair94 <notifications@github.com> wrote:  
 
 
When I go through and fix these, someone from m3 will have to be in attendance to learn how to fix the cost and gate

**Comment by NSinclair94** [comment]
I'm not around next weekend, and potentially the weekend after. If you take pictures of all the damage and put them on here I can tell you what needs doing

**Comment by NSinclair94** [comment]
Under no circumstances are you to take collars off of other blades. You broke the blades, therefore you must settle for M4 until they are fixed

**Comment by Terywall** [comment]
Noted moving forward.  The collar has however been changed now (removed from an M4 blade).  The broken collar is on your desk/table and Claudio left the collarless M4 blade on the side.  Happy to change it back if that’s what you prefer, although makes more sense to keep it on the M3 blades as M4 aren’t being used I believe. Let us know what you would prefer we do.

**Comment by NSinclair94** [comment]
So now there are 2 blades (1xm3 and 1xm4) out of action?

**Comment by Terywall** [comment]
I changed it but I can’t remember if it was Eyal or Louise who asked me to
change it. All M3 blades are in working order now.  Only 1x M4 blade now
has no collar.  The blade is where you suggested to leave it Claudio and
the the broken collar is on Nicks table/desk

**Comment by eyalpole** [comment]
Ok - lesson learnt for next time!  The idea was to avoid people using a blade with a broken collar.

Eyal    On Wednesday, 23 May 2018, 08:24:51 BST, NSinclair94 <notifications@github.com> wrote:  
 
 
The collar should never have been removed in the first place, then should have been put back on the M4 blade

**Comment by NSinclair94** [comment]
I will put a new collar on the bench for you to put on the m3 blade tonight, please make sure it goes on the m3 blades and not the M4 one.

**Comment by NSinclair94** [comment]
Found a collar, located next to the blade that was left at the front of the boathouse, as opposed to the back where I was told it was left

**Comment by Terywall** [comment]
No idea.  Someone from our outing must have picked it up and put it there.

**Comment by eyalpole** [comment]
at the end I had no outing this morning so didn't fix the blade.
Eyal can you and Omar do it tomorrow morning?

Claudio

**Comment by Terywall** [comment]
Sure, no problem.
