### ISSUE TITLE
Stern-Scratches

### ISSUE THREAD

**Issue by eyalpole** [CityRC/Equipment#262]
### Some scratching on Stern

(Louise asked to report)

**Comment by NSinclair94** [comment]
How.

**Comment by 13enedict** [comment]
...anything...

**Comment by eyalpole** [comment]
Ask your other half.  I am just the messenger.
    On Sunday, 20 May 2018, 16:28:41 BST, NSinclair94 <notifications@github.com> wrote:  
 
 
How.

**Comment by NSinclair94** [comment]
You lot should really be more careful, luckily it's only cosmetic....

**Comment by eyalpole** [comment]
Nick - have you every heard of killing the messenger 😉
    On Wednesday, 23 May 2018, 18:32:13 BST, NSinclair94 <notifications@github.com> wrote:  
 
 
You lot should really be more careful, luckily it's only cosmetic....
