### ISSUE TITLE
CAM200 Ultra steering footplate has a growing crack in it

### ISSUE THREAD

**Issue by 13enedict** [CityRC/Equipment#263]
### Boat name or ID
CAM200 Ultra 

### Problem description
The holes on the left-hand-side of the steering footplate are beginning to crack. 

### Seat number(s) affected
Bow

**Comment by NSinclair94** [comment]
Knew you would break something

**Comment by 13enedict** [comment]
Pretty sure it's been gone for a while

**Comment by NSinclair94** [comment]
Should we put the new jupton footplate on ultra seeing as jupton is never used as a pair and is pointless having a steering footplate on it

**Comment by 13enedict** [comment]
New footplate has been ordered

**Comment by 13enedict** [comment]
Can probably wait until next week

**Comment by NSinclair94** [comment]
Happy to do this tomorrow

**Comment by 13enedict** [comment]
Assuming this is fixed; if not the footplate has arrived.
