### ISSUE TITLE
Caroline & Joanne: nuts, lips, bushes

### ISSUE THREAD

**Issue by DarthSlater** [CityRC/Equipment#264]
C&J: the boat of a thousand washers

This boat is like the Bermuda Triangle when it comes to parts just vanishing. I blame everyone else for this.

It's going to Nottingham this sat and really needs a a good look over by a man with decent parts if possible. We have missing bushes (this  is a bad thing, honest), most likely the corresponding bush nuts missing too and a huge amount of large washers stacked up as substitutes. 

One for a meccano enthusiast

**Comment by 13enedict** [comment]
It'd need to be derigged, the carbon lip bushes bolted on and glued in
place, and then a hex placed on them by a witch to further stop idiots from
removing them.

**Comment by DarthSlater** [comment]
You can always count on a witch to have a hex key....

**Comment by 13enedict** [comment]
When derig for race?

**Comment by DarthSlater** [comment]
As we're rowing in it Thursday and Friday night and de-rigging after Friday's outing, I think logistically this will have to wait til we come back.  Thanks Benedict

**Comment by DarthSlater** [comment]
And now a hatch cover is missing
I blame trailer thieves

**Comment by 13enedict** [comment]
I'd log it separately or it'll get forgotten about

**Comment by 13enedict** [comment]
Assuming this is fixed as no-one has arranged mending
