### ISSUE TITLE
Caroline & Joanne: hatch cover missing

### ISSUE THREAD

**Issue by DarthSlater** [CityRC/Equipment#265]
Hatch cover gone walkabout.  Was on boat on trailer in Notts then magically disappeared

**Comment by NSinclair94** [comment]
Benedict, we will have to pay a visit to that magic hatch cover tree again

**Comment by 13enedict** [comment]
We actually do have some spares. Will take an hour to fit with crew help.

**Comment by 13enedict** [comment]
Assuming this is fixed

**Comment by DarthSlater** [comment]
I don't think it is? Plus no hatch cover

**Comment by 13enedict** [comment]
Then you'll need to arrange a maintenance session to tie on remaining hatch
covers and fit new...

**Comment by 13enedict** [comment]
Assuming this is fixed.
