### ISSUE TITLE
M1 blades a mess

### ISSUE THREAD

**Issue by stigweed** [CityRC/Equipment#267]
Paint flaking off but, more seriously, worn down and delaminated, filling up with mud and grit.

Nick and I have built up the ends of 4 of them (using dams and 5min epoxy). Sanding down later today.

Not sure when I'll get a chance to do the other four. Focusing on a set for the 4- to look up to scratch for Henley etc.

**Comment by stigweed** [comment]
Update: I will rebuild the ends of the other 4 blades tomorrow (Sunday) morning, and I guess sand down on Monday.

Navy blue paint on the other 4 seems to be doing OK too. Claret stripe is holding up. The yellow stripes from Mackays are not doing as well and loose dog-ears have been trimmed off. Need to find something better (not shiny gold)... but will continue with existing materials on the other 4 blades so they match for bumps.

**Comment by 13enedict** [comment]
I should point out that they will get repainted in the canonical colours
(probably including a less tacky shiny gold) when we get source the right
materials

**Comment by stigweed** [comment]
Yes I know this. Just want them to match for bumps. You might as well focus
on the other club blades at that point as these will then hold up for a
while (if not most of the season).

**Comment by 13enedict** [comment]
OK, cool

**Comment by 13enedict** [comment]
Assuming that this is sorted. Pls reopen if not
