### ISSUE TITLE
Eddy leg steering tight

### ISSUE THREAD

**Issue by jamesboonzaier** [CityRC/Equipment#270]
Eddy legg

Steering cables tight, can't move rudder. Shoes broken too, so steering foot is loose. 

Rails loose and seat bearings noisy and rough AF. 

Bow.

**Comment by NSinclair94** [comment]
Shouldn't be using foot steering for a double. 
The rails can be tightened, there are thumb screws underneath them.
The noisy seat bearings need some oil applied to them.

**Comment by 13enedict** [comment]
Eddie Legge just is a bit tight, it's very usable, I steered it at Pairs Head...
