### ISSUE TITLE
Tony's fin

### ISSUE THREAD

**Issue by stigweed** [CityRC/Equipment#271]
Fin was coming loose. We have taken it out to dry before filling in with putty again. Please do not use. Fin is taped to a rigger.

Nick do you have any plumbers putty in?

**Comment by NSinclair94** [comment]
Does it not have the screw which holds it in place?
We do have some plumbers silicon (the stuff you pump out using the weird gun thing)

**Comment by stigweed** [comment]
Yes screw still there but the fun itself was rattling.

**Comment by NSinclair94** [comment]
Maybe try silicon then? When Benedict gets up he may have a suggestion

**Comment by 13enedict** [comment]
Yeah, don't use filler, it will cause problems; use silicone if anything. Unless it's very loose, I wouldn't regard it as a problem, it shouldn't affect steering.
