### ISSUE TITLE
CAM013 Doreen Halifax stroke rate meter does not work

### ISSUE THREAD

**Issue by nzia1** [CityRC/Equipment#4]
Rate meter doesn't work

**Comment by 13enedict** [comment]
This needs a new stroke meter, we don't have any in stock. Ideally, I would like to wait until after the next committee meeting to order as we may be ordering some other wiring.

**Comment by nzia1** [comment]
Whats another month or 2 when it hasn't been working in so long?? Just gives me longer to annoy you about fixing it :+1:

**Comment by 13enedict** [comment]
Should be fixed (hooray); I've fitted a new stroke rate meter but haven't tested yet. If you wouldn't mind letting me know how it goes...

**Comment by nzia1** [comment]
Haven't taken Doreen out in a while but will let you know how it goes next time i do..

**Comment by Seb-Walker** [comment]
The stroke rate meter wasn't working for Hammersmith Head or last weekend

**Comment by nzia1** [comment]
It hasn't worked in a long while. Jack suspects it might be the wiring and position of the magnet.

**Comment by Jess-upton** [comment]
This is a duplicate report - so this item is closed and most recent report is left open
