### ISSUE TITLE
Cox Life jacket inspection and update gas cartridges

### ISSUE THREAD

**Issue by ianwellwood** [CityRC/Equipment#47]
Hi Benedict,
Just to check if we can keep this task on the calendar (6 monthly)- from the annual safety audit. The following work should be carried out please:

Lifejackets (PFD) need to be inspected 
Can we somehow label / mark them so they can be identified.
Need to check the sell by date on gas cannisters that inflate the vest
If out of date - obtain and fit new cannister kit.
Create a log / record of inspection and upkeep (any suggestions how best to do this ? electronic record??)

Thanks - happy to discuss if you need more info,
Cheers, Ian

**Comment by umarndt** [comment]
i would recommend a google doc, easiest way to keep track. I will label the jackets this week

**Comment by 13enedict** [comment]
It looks like gas cartridges don't expire however the life jackets do need inspecting and given their importance that's something that I'm not taking responsibility for. I'll bring it up at the next committee meeting.
