### ISSUE TITLE
Doreen dent/crack in canvass

### ISSUE THREAD

**Issue by Seb-Walker** [CityRC/Equipment#62]
The skin of the canvass on Doreen has been dented and cracked.  Looks like it was caused by being tied on too tight on the trailer with no protection on the way back from HoRR

**Comment by 13enedict** [comment]
Did any part of Doreen survive intact??

**Comment by Seb-Walker** [comment]
It wasn’t a great journey.  We lost 3 bolts on the way down (consuming all of the spares that I had taken down) and one fell out on the way back but was recovered in the trailer.

**Comment by JackLA** [comment]
is the crack down the keel around the 5 seat?

**Comment by Seb-Walker** [comment]
No it's on the bow canvas. Looks like the bows were resting on a bar of the trailer with nothing to pad them and then strapped on so tightly that the "spine" running from the bow seat to bow was crushed by the trailer's bar.

**Comment by JackLA** [comment]
OK I'm off work tomorrow so (Benedict) if you fancy doing some repairs I'm
going to be in the clubhouse once I've inspected Clare's ergs at 11

**Comment by 13enedict** [comment]
OK, I think that should be fine, see at you at 11. Here's a photo of the damage, for reference:
![image](https://cloud.githubusercontent.com/assets/9012054/13984641/771577d4-f0ef-11e5-9f20-0c54e9c00c03.png)
