### ISSUE TITLE
Liberty 

### ISSUE THREAD

**Issue by CCRCJuniors** [CityRC/Equipment#69]
There is a gash in the hull of Liberty, looks like it might be being worked on, recently sanded?, the junior girls noticed in on Sat when putting it back on the racks. We put some tape on it, but should be looked at.

**Comment by CCRCJuniors** [comment]
There are 2 gashes, pictures below.  

![liberty_gash_20160411](https://cloud.githubusercontent.com/assets/15690308/14442550/3fd2dd14-0032-11e6-8940-d92f31cd4656.jpg)
![liberty_gash 2_20160411](https://cloud.githubusercontent.com/assets/15690308/14442599/88a559f4-0032-11e6-8010-d8a247ffe5b7.jpg)

**Comment by JackLA** [comment]
Benedict fancy having a repair session on Saturday?

**Comment by CCRCJuniors** [comment]
sorry :(  If we (juniors) can help with anything, let me know, once C&J is
fixed and we will rig it.  I should get them all down for a boat cleaning
session.  I'll look into getting something on the calendar.
I have no idea how that happened with the steering handle, didn't even know
it could move on that much on an arc.

Cheers
T

On 11 April 2016 at 22:29, JackLA <notifications@github.com> wrote:

> Benedict fancy having a repair session on Saturday?
>
> On 11 April 2016 at 22:13, CCRCJuniors <notifications@github.com> wrote:
>
> > There are 2 gashes, pictures below.
> >
> > [image: liberty_gash_20160411]
> > <
> https://cloud.githubusercontent.com/assets/15690308/14442550/3fd2dd14-0032-11e6-8940-d92f31cd4656.jpg
> >
> > [image: liberty_gash 2_20160411]
> > <
> https://cloud.githubusercontent.com/assets/15690308/14442599/88a559f4-0032-11e6-8010-d8a247ffe5b7.jpg
> >
> >
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly or view it on GitHub
> > <https://github.com/13enedict/CCRC/issues/69#issuecomment-208563637>
> >
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/13enedict/CCRC/issues/69#issuecomment-208571277>
>



-- 
Tammy Finnigan
CCRC Junior Squad Co-ordinator
Mobile: 07920016476

**Comment by 13enedict** [comment]
I sanded the top one just to stop damage getting any worse. I had a look it the other day when somebody was convinced it had penetrated the hull. It hasn't and just needs patching up.

I should be around on Saturday, @JackLA that sounds good to me. Quite a bit of hull damage needs repairing across the fleet.
