### ISSUE TITLE
Laurie Numbering Plate

### ISSUE THREAD

**Issue by colmcmurphy** [CityRC/Equipment#76]
When Laurie was being taken out 03/05/16, the black numbering plate by the bow end hit a rigger from another boat. The impact created a small hole, which was temporarily covered with tape. The hole is large enough to cause leakage unfortunately and will need to be filled.

**Comment by 13enedict** [comment]
Do you mean the number plate holder? On top of the boat?

**Comment by colmcmurphy** [comment]
Yes sir. The holder moved forwards, when caught by the rigger, creating a hole underneath. Should be visible at the side of the holder.

**Comment by 13enedict** [comment]
Glued a new one on
