### ISSUE TITLE
Claire Berryman Speakers

### ISSUE THREAD

**Issue by CCRCJuniors** [CityRC/Equipment#78]
The speakers in Claire Berryman are not working, they have been intermittent over the last couple of weeks but wasn't sure if it was the cox box microphone but this weekend I tested it with my own cox box and neither speakers are working.  We can leave it on trestles in the boat bay this evening if this would be helpful?

Thanks
Tammy

**Comment by JackLA** [comment]
The speakers in this are the old sims ones so potentially will need a
complete new loom

**Comment by CCRCJuniors** [comment]
What does this mean?  Do we need to get a price and approval from the committee?

**Comment by 13enedict** [comment]
I have scavenged the speakers from King and we already have the wiring loom so potentially, it's just a few brackets and the fitting that needs to be done.

**Comment by CCRCJuniors** [comment]
When can we make a start? By we, I mean you :) although happy to help if I/we(jnrs)?can.

**Comment by 13enedict** [comment]
I'll have to get the fixings ordered in but otherwise, yeah, I think so

**Comment by 13enedict** [comment]
Actually, it would be sensible for us to order a new 4-2 wiring harness so that we still have the spare parts in case anything breaks
