### ISSUE TITLE
Hatch covers

### ISSUE THREAD

**Issue by CCRCJuniors** [CityRC/Equipment#79]
There are missing hatch covers for the Stampfli 4s, we had to borrow 2 from Angles&Daemons to put in Caroline&Joanne, Angels was already missing 2.  We did try to find ones that would fit from the spares, but no luck.  I think we need to order at least 2 covers.  

If both boats are racing at the weekend, you might need to check if the covers in liberty fit.

Cheers
T

**Comment by 13enedict** [comment]
I sent Duncan to Nottingham with four spare Stämpfli hatch covers; has this been sorted?

**Comment by 13enedict** [comment]
Replacements should be arriving in the next few days

**Comment by 13enedict** [comment]
Replaced hatch covers on Angels & Daemons and have spares for C&J but since then another appears to have gone missing so still short
