### ISSUE TITLE
Sculling blades

### ISSUE THREAD

**Issue by CCRCJuniors** [CityRC/Equipment#80]
The sculling blades are looking rather tired, I spoke to one of the repair stands at Dorney yesterday and they quoted £28 to refurb each blade.  The jnr foodstall raised over £500 at the big weekend and the taster days have brought in around £1200 this yr,  I'd like to propose we use some of this to have the blades refurbished.  We have 16 sets, 3 are new, so total cost would be £812 + VAT, we might want to select the worst of them and start there.  They will do them onsite, so not need to have them sent off anywhere.
It's the same company that many of the colleges use, Emma, Maggie, Queens so are in Cambridge quite regularly.  If no objections or other suggestions I will put forward to committee.

We should probably find a weekend to get them re-painted too.

Cheers
T

**Comment by 13enedict** [comment]
Sounds good to me, some of the sculling spoons are in a pretty awful condition and we they all need a repaint, anyway.

**Comment by 13enedict** [comment]
Juniors have sorted, blades are being sent off
