### ISSUE TITLE
Seats

### ISSUE THREAD

**Issue by JackLA** [CityRC/Equipment#81]
Currently Claire Berryman (coxed quad outside) has Carbon Stampfli seats. Although using King's seats to make up the missing ones. We have several wooden seats at the back of the boat house we could "fix up" and put in Claire, this would then take the expensive Carbon seats out and they can be put in Angels which seams to have lost it's seats to Doreen.

Which ever way its done, we should make the wooden seats good to use and take make sure all boats have fixed seats in again.

**Comment by 13enedict** [comment]
A thought occurs. What about the seats in Ontario? Surely we don't need two
coxed quads?

**Comment by CCRCJuniors** [comment]
Both quads are being used at the moment.

**Comment by JackLA** [comment]
If we have a surplus of seats (fixing up the ones at the back) then we are out of the woods and we don't need to buy any more. However seats from out top boats are getting dragged in and out of boats left right and centre - and we need to rectify this asap
