### ISSUE TITLE
Stämpfli / Janousek Pins

### ISSUE THREAD

**Issue by JackLA** [CityRC/Equipment#83]
Used Pin off sweep riggers for Jess Upton to replace pin on Laurie as the top nut was ceased inside. Possibly need a couple of replacement Stampli pins as the current ones in stoke are Filippi.

**Comment by 13enedict** [comment]
These have been ordered and should arrive soon

**Comment by 13enedict** [comment]
These have arrived, they're in the cupboard at the back
