### ISSUE TITLE
CAM # for Empacher 1x

### ISSUE THREAD

**Issue by CCRCJuniors** [CityRC/Equipment#89]
Hi there

Could you advise the next available CAM registration #? We will need to register the boat before the next off Cam race which is likely to be Marlow on 18th Jun.

Thanks!
Tammy

**Comment by 13enedict** [comment]
Number is CAM119, I'll get stickers for it

**Comment by CCRCJuniors** [comment]
Thanks. And we can close the item for the new shoes, apparently they have 'loosened' either that or his feet have shrunk :)
