### ISSUE TITLE
Reedham shoes 

### ISSUE THREAD

**Issue by susannevalen** [CityRC/Equipment#92]
The right shoe at seat 6 in Reedham needs to be reattached with screws/bolts as it is currently totally disattached from the footplate. It is currently held in place by duck tape.

**Comment by umarndt** [comment]
We took the shoes to the boathouse, the screws are not held on the plate
any more, needs either washers or a new shoe plate by tonights outing.
Ursula

**Comment by 13enedict** [comment]
Replaced shoe plate
