### ISSUE TITLE
Redeham Bumps Damage

### ISSUE THREAD

**Issue by nathalieflower** [CityRC/Equipment#93]
Hiya, 

Redehams bow canvas was damaged during loan to Homerton during May Bumps, we may need to send it to Ian Watson? Or another boatman for repair. 

Are we able to get a quote so I can send it to Homerton.

Best wishes,

Nathalie

**Comment by 13enedict** [comment]
I think we're kicking this into the long grass until after bumps, it will need new boat name stickers. The current ones are 75mm tall and use the "Bookman Headline" typeface

**Comment by Jess-upton** [comment]
Hi
Can I have an update on this repair at some point please?  I don't want to continue with this being fixed with Duct Tape as it is now, and really need it repaired in time for racing in the new year.
Thanks
Jess

**Comment by 13enedict** [comment]
@JackLA said he would deal with this one. Last time I asked, he was waiting for Ian to get back to him.

**Comment by 13enedict** [comment]
This has been sent to Downing to be repaired
