### ISSUE TITLE
Creme rudder

### ISSUE THREAD

**Issue by gdg23** [CityRC/Equipment#95]
As discussed - if possible could we get a smaller rudder for Creme? It is currently quite difficult to steer, and the harsh ruddering makes rowing the boat tricky (admittedly some of that is just my steering being pretty poor, but...)

Thanks
Guy

**Comment by JackLA** [comment]
Cut the rudder in half

**Comment by gdg23** [comment]
If chopping the rudder is an option that's fine by me

**Comment by 13enedict** [comment]
We'll call that plan B, I'll see if I can get a proper rudder for it

**Comment by JackLA** [comment]
I really wouldn't bother.... just cut it in half that's what we did to the
Filippis
