### ISSUE TITLE
Reedham - bow ball missing 

### ISSUE THREAD

**Issue by tristanjph2** [CityRC/Equipment#97]
Bow ball completely missing now. Needs replacing asap for timed race on Thursday.

**Comment by JackLA** [comment]
How is this missing another bow ball???????

Are we landing the boats at high speed - or are we just hitting everything
on the river?

**Comment by tristanjph2** [comment]
No idea... was completely missing when we got it out yesterday!

**Comment by 13enedict** [comment]
Unbelievable. I'm going to get some extra big bow balls for Redeham
