### ISSUE TITLE
4 Seat Shoes in Wholly

### ISSUE THREAD

**Issue by AubreeW** [CityRC/Equipment#99]
The shoes at the 4 seat in Wholly have lost their velcro and don't stay strapped.  Not sure if anyone is rowing in this boat for bumps, but I ended up wrapping tape around the shoes to try to keep my feet in during last night's outing.

**Comment by 13enedict** [comment]
New shoes have arrived from supplier

**Comment by 13enedict** [comment]
Had a look at the four shoes on CAM018 Wholly Spirited. They seem to be fine. Please could you check that this is the seat that you mean and if you like, show  me the problem
